AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  anthropic-mongodb-bot

  Sample SAM Template for anthropic-mongodb-bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120
    MemorySize: 512

Resources:
  AnthropicMongoDBAgentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaExecute # Managed policy for writing logs
        - AmazonBedrockFullAccess
        - SecretsManagerReadWrite
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AnthropicMongoDBAgentFunction:
    Description: "Anthropic MongoDB Agent Lambda Function ARN"
    Value: !GetAtt AnthropicMongoDBAgentFunction.Arn
  AnthropicMongoDBAgentFunctionIamRole:
    Description: "Implicit IAM Role created for Anthropic MongoDB Agent"
    Value: !GetAtt AnthropicMongoDBAgentFunctionRole.Arn
